# Generated by Django 4.1.1 on 2022-09-14 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0002_review_streamplatform_watchlist_delete_watchmate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streamplatform',
            name='website',
        ),
    ]
