# Generated by Django 4.1.1 on 2022-09-14 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0010_review_review_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review_user',
        ),
    ]
