# Generated by Django 4.1.1 on 2022-09-14 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0015_remove_review_watchlist_alter_review_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='watchlist',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to='learning_app.watchlist'),
            preserve_default=False,
        ),
    ]
